# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/99_main.ipynb (unless otherwise specified).

__all__ = ['get_parser']

# Cell
import argparse


# Cell

def get_parser():
    parser = argparse.ArgumentParser(
        description="Tool for converting datasets in COCO format between different formats"
    )
    subparsers = parser.add_subparsers(help='mode')
    parser_convert = subparsers.add_parser('a', help='a help')

    parser.add_argument("--src-jsonfile", type=Path, required=False)
    parser.add_argument("--src-jsontree", type=Path, required=False)
    parser.add_argument("--src-blobtree", type=Path, required=False)
    parser.add_argument("--dst-jsonfile", type=Path, required=False)
    parser.add_argument("--dst-jsontree", type=Path, required=False)
    parser.add_argument("--dst-blobtree", type=Path, required=False)
    return parser
