# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"logger": "90_cli.ipynb",
         "sort_dict": "00_utils.ipynb",
         "sanitize_filename": "00_utils.ipynb",
         "read_image": "00_utils.ipynb",
         "download_image": "00_utils.ipynb",
         "draw_image": "00_utils.ipynb",
         "cut_bbox": "00_utils.ipynb",
         "write_image": "00_utils.ipynb",
         "CocoElement": "01_coco.ipynb",
         "CocoInfo": "01_coco.ipynb",
         "CocoLicense": "01_coco.ipynb",
         "CocoImage": "01_coco.ipynb",
         "CocoAnnotation": "01_coco.ipynb",
         "CocoObjectDetectionAnnotation": "01_coco.ipynb",
         "CocoCategory": "01_coco.ipynb",
         "CocoObjectDetectionCategory": "01_coco.ipynb",
         "CocoDataset": "01_coco.ipynb",
         "CocoObjectDetectionDataset": "01_coco.ipynb",
         "get_dataset_class": "01_coco.ipynb",
         "MAP_COCO_TYPE_TO_DATASET_CLASS": "01_coco.ipynb",
         "merge_datasets": "01_coco.ipynb",
         "shuffle": "01_coco.ipynb",
         "cut_annotations_per_category": "01_coco.ipynb",
         "load_json_file": "02_json_file.ipynb",
         "dump_json_file": "02_json_file.ipynb",
         "load_json_tree": "03_json_tree.ipynb",
         "dump_json_tree": "03_json_tree.ipynb",
         "load_crop_tree": "04_crop_tree.ipynb",
         "dump_crop_tree": "04_crop_tree.ipynb",
         "get_parser": "90_cli.ipynb",
         "main": "90_cli.ipynb"}

modules = ["utils.py",
           "coco.py",
           "json_file.py",
           "json_tree.py",
           "crop_tree.py",
           "main.py"]

doc_url = "https://invalid/cocorepr/"

git_url = "https://github.com/neuro-inc/cocorepr"

def custom_doc_links(name): return None
