package:
  name: cocorepr
  version: 0.0.1
source:
  sha256: 94b008b7b614ebc913e7edf821b3cbb0fe16eb6e9902633cd8bfb071ad710ca5
  url: https://files.pythonhosted.org/packages/2d/e7/7dea7e7051cfdc6d85eabbe3c5cc9e8ab1e25f664ff2e174d2ebd1b7e774/cocorepr-0.0.1.tar.gz
about:
  dev_url: https://invalid
  doc_url: https://invalid
  home: https://invalid
  license: Apache Software
  license_family: APACHE
  summary: COCO Dataset cleaning tool
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - artemlops
requirements:
  host:
  - pip
  - python
  - packaging
  run:
  - pip
  - python
  - packaging
test:
  imports:
  - cocorepr
